import type { Metadata } from "next";
import Navigation from "./components/navigation";
import "../styles/global.css";

export const metadata: Metadata = {
  title: "Next Js 14 Start",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
